name: myfrontflutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

# CAMBIADO: Ajustado a la versión de Dart de Flutter 3.10.6
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Plugins base (versiones estables) ---
  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  shared_preferences: ^2.1.1
  path: ^1.9.0

  # --- PLUGINS REBAJADOS PARA COMPATIBILIDAD CON ANDROID 5 ---

  # (Toast v8 es mucho más estable en APIs viejas)
  fluttertoast: ^8.2.4

  # (Camera v0.9 usa Camera2, no CameraX, y es compatible con hardware antiguo)
  camera: ^0.9.8+1

  # (Versiones de 2023 que aún soportaban API 21)
  video_player: ^2.7.2
  path_provider: ^2.1.1
  permission_handler: ^10.4.5
  share_plus: ^7.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 # Bajado de 5.0.0 a 2.0.0 para ser compatible con Dart 3.0.6


flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg